# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-23 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_to_news_updates', models.BooleanField(default=False, verbose_name=b"Je souhaite \xc3\xaatre inform\xc3\xa9-e de l'actualit\xc3\xa9 de Rue89/l'Obs et de la parution de ses futures MOOCs")),
                ('accept_terms_of_use_of_personal_data', models.BooleanField(verbose_name=b"j'accepte les conditions d'utilisation des donn\xc3\xa9es personnelles")),
                ('accept_privacy_policy', models.BooleanField(verbose_name=b'J\xe2\x80\x99accepte la politique de confidentialit\xc3\xa9 de Rue89 MOOC')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
